name: Label PRs

on:
  # Note: https://github.com/actions/labeler/issues/121
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    # Add labels based on contents of .github/labeler.yml
    steps:
      - uses: actions/labeler@5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
